plugins {
    id 'java'
    id 'application'
}

group = 'com.zatuna'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'com.zatuna.library.LibraryApp'
}

run {
    standardInput = System.in
}

repositories {
    mavenCentral()
}

dependencies {
    // Database: PostgreSQL Driver
    implementation 'org.postgresql:postgresql:42.7.11'
    implementation 'com.h2database:h2:2.2.224'

    // Logging: SLF4J API + Logback Implementation
    implementation 'org.slf4j:slf4j-api:2.0.12'
    implementation 'ch.qos.logback:logback-classic:1.5.3'

    // Testing: JUnit 5 & Mockito
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes 'Main-Class': 'com.zatuna.library.LibraryApp'
    }
}
